### ISSUE TITLE
Create a carousel display component

### ISSUE THREAD

**Issue by CameronJung** [gurtejboparai/bookwyrm#212]
The elements in the carousel displays for the front end will probably need a vue component to display their data in the carousel. Ideally this component should be able to be used for each carousel.

**Comment by LukeBMorrow** [comment]
Run for loop to call java endpoint specifc to issue (top or newest) once per genre.
Turn top/newest books into a dictionary of the form {genre:book, genre2:book2, ...}
Make a component that takes in a prop dictionary with form {genre:book, genre2:book2, ...}
Create carousel in component
Create v-for to loop through books in dictionary making carousel item for each book.
