### ISSUE TITLE
Add component to display reviews

### ISSUE THREAD

**Issue by LukeBMorrow** [gurtejboparai/bookwyrm#36]
Add Vue component to display information relating to a review. This will likely hold a data object (JSON) with the following fields:
{
Date,
rating,
title,
description,
author,
anonymous (check before accessing author B/C author might be null)
}

**Comment by CameronJung** [comment]
I think this might be more complicated than a single vue component. If reviews are going to have a comments section than they will probably need their own page to display a single review. Meanwhile the book details page should probably have the ability to display multiple reviews in a more compact form, this might need a separate component.

**Comment by LukeBMorrow** [comment]
We could handle it in a number of ways, I'll list a few just to get some ideas out there:  
- We could make reviews a popup with comments on the popup,  
- We could have the reviews in full on the book detail page, but minimize the comments unless the user clicks to see comments.  
- We could redirect to a review specific page  
- We could redirect to a review list page, with all the reviews for a single book on a single page.  

I'm sure there are more options, but whats nice about Vue is that you can move where the components are placed without needing to rework the entire app if we change our minds.

**Comment by CameronJung** [comment]
I have an idea for what to do know, I think we could discuss it at our next meeting.
